logging:
  level:
    root: info
    com.nuvu.corenuvu: DEBUG

server:
  servlet:
    context-path: /
  port: 8080
  error:
    include-stacktrace: NEVER
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/corenuvudb?currentSchema=public&ApplicationName=Business
    username: postgres
    password: adminadmin  
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true







